runtime: nodejs18

instance_class: F2

env_variables:
  FIREBASE_WEB_API_KEY: ''
  FIREBASE_PROJECT_ID: ''
  FIREBASE_CLIENT_EMAIL: ''
  FIREBASE_PRIVATE_KEY: ''
  GOOGLE_APPLICATION_CREDENTIALS: "service-account-file.json"
  FIREBASE_DATABASE_URL: ""

handlers:
  - url: /health
    script: auto
    secure: always
  - url: /.*
    script: auto
    secure: always

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  initial_delay_sec: 300

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2
